CREATE TABLE [EventTypes] 
(
    [Id] VARCHAR(20) PRIMARY KEY,
    [NameFr] NVARCHAR(50),
    [ColorLight] NVARCHAR(7) NOT NULL DEFAULT '#FFFFFF',
    [ColorDark] NVARCHAR(7) NOT NULL DEFAULT '#FFFFFF',
	[Image] VARCHAR(MAX),
    [CreatedAt] DATETIME NOT NULL DEFAULT GETDATE(),
    [UpdatedAt] DATETIME NULL
);